services:
  app:
    build: .
    image: growme/app:dev
    environment:
      SPRING_PROFILE: dev
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: growme
      DB_USERNAME: root
      DB_PASSWORD: root1234
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: growme
      MYSQL_ROOT_PASSWORD: root1234
      TZ: Asia/Seoul
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot1234 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: