spring:
  application:
    name: growme
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config.activate.on-profile: local
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/growme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6699e3a56fa823259747625897e29c6f             # Kakao REST API 키
            client-secret: DqChxaaDLsrynsHnUDsAQMJ8mGeq2xW9    # 시크릿 미사용 시 비워둬도 OK
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  data:
    redis:
      host: localhost
      port: 6379

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173"

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    access-token-minutes: 60

---
spring:
  config.activate.on-profile: dev

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



---
spring:
  config.activate.on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  tomcat:
    threads:
      max: 200