spring:
  application:
    name: growme
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: local

server:
  port: 8080

management:
  endpoints.web.exposure.include: "health,info,metrics"
  endpoint.health.probes.enabled: true

---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/growme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173"
security:
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    access-token-minutes: 60

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
  data.redis.host: ${REDIS_HOST}
  data.redis.port: ${REDIS_PORT:6379}

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
  data.redis.host: ${REDIS_HOST}
  data.redis.port: ${REDIS_PORT:6379}
server:
  tomcat:
    threads:
      max: 200