name: Deploy Dev

on:
  push:
    branches: [ develop ]

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write   # GHCR 푸시에 필요
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY }}/growme
          tags: |
            type=raw,value=dev
            type=raw,value=sha-${{ github.sha }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ${{ secrets.REGISTRY }}/growme:sha-${{ github.sha }} || docker pull ${{ secrets.REGISTRY }}/growme:dev
            docker rm -f growme || true
            docker run -d --name growme -p 8080:8080 \
              -e SPRING_PROFILE=dev \
              -e DB_HOST='${{ secrets.DB_HOST }}' \
              -e DB_PORT='${{ secrets.DB_PORT }}' \
              -e DB_NAME='${{ secrets.DB_NAME }}' \
              -e DB_USERNAME='${{ secrets.DB_USERNAME }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e REDIS_HOST='${{ secrets.REDIS_HOST }}' \
              -e REDIS_PORT='${{ secrets.REDIS_PORT }}' \
              ${{ secrets.REGISTRY }}/growme:sha-${{ github.sha }}